### Combining arrays

** First ** we need to import numpy library

In [27]:
import numpy as np

** Then ** we create a first array with numbers from 1 to 5

In [33]:
# set up 1-d array
array1 = np.arange(1, 6)
array1

array([1, 2, 3, 4, 5])

** As the next step ** we create another array with numbers from 10 to 14

In [34]:
array2 = np.arange(10, 15)
array2

array([10, 11, 12, 13, 14])

** Finally ** we create one more array with numbers from 30 to 34

In [43]:
array3 = np.arange(30, 35)
array3

array([30, 31, 32, 33, 34])

*NOTE*  that both arrays are of the same size

Now we can stack these arrays as a **column**, in this case each array in the stack will be combined from a value from the same position in each array

In [44]:
np.column_stack((array1, array2, array3))

array([[ 1, 10, 30],
       [ 2, 11, 31],
       [ 3, 12, 32],
       [ 4, 13, 33],
       [ 5, 14, 34]])

We also can stack these arrays as a **rows**, in this case each array in the stack will be added to the stack as a whole

In [41]:
np.row_stack((array1, array2, array3))

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [30, 31, 32, 33, 34]])